config/routes.rb
Pippin::Application.routes.draw do


  resources :categories do
      resources :events
  end
  
  resources :venues

  get 'about' => 'welcome#about'
  
  devise_for :users

  root to: 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :events
  belongs_to :parent, class_name: 'Category'
  has_many :subcategories, class_name: 'Category', foreign_key: :parent_id, :dependent => :destroy
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :parent, class_name: 'Event'
  has_many :events, foreign_key: :parent_id
  has_and_belongs_to_many :venues
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_and_belongs_to_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.where(parent_id: nil).to_a
  end

  def show
    @category = Category.find(params[:id])
    @subcategories = @category.subcategories.to_a
    @events = @category.events
  end

  def new
    @category = Category.new
    @category.parent = Category.find(params[:id]) unless params[:id].nil?
  end

  def create
    @category = Category.new(category_params)
    @category.parent = Category.find(params[:id]) unless params[:id].nil?
    if @category.save
      flash[:notice] = "Category was saved."
      redirect_to categories_path
    else
      flash[:error] = "There was an error saving the category. Please try again."
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Category was updated"
      render :index
    else
      flash[:error] = "There was an error saving the category. Please try again."
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:notice] = "Category was deleted."
      redirect_to categories_path
    else
      flash[:error] = "There was an error deleting the category. Please try again."
      render :index
    end
  end


  private

  def category_params
    params.require(:category).permit(:name, :id, :parent_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @events = @category.events
  end

  def show
    @category = Category.find(params[:category_id])
    @event = Event.find(params[:id])
  end

  def new
    @categories = Category.all
    @category = Category.find(params[:category_id])
    @event = Event.new
  end

  def create
    @category = Category.find(params[:category_id])
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event was saved."
      redirect_to [@category, @event]
    else
      flash[:error] = "There was an error saving the event. Please try again."
      render :new
    end
  end

  def edit
    @categories = Category.all
    @category = Category.find(params[:category_id])
    @subcategories = @category.subcategories.to_a
    @event = Event.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = "Event was updated"
      redirect_to [@category, @event]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end


  private

  def event_params
    params.require(:event).permit(:title, :body, :price, :category_ids)
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      flash[:notice] = "Venue was saved."
      redirect_to @venue
    else
      flash[:error] = "There was a problem saving the venue. Please try again."
      render :new
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    if @venue.update_attributes(venue_params)
      flash[:notice] = "Venue was updated."
      redirect_to @venue
    else
      flash[:error] = "There was an error saving the venue. Please try again."
      render :edit
    end
  end




  private

  def venue_params
    params.require(:venue).permit(:name, :body, :address, :phone, :website)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<div class="row">
  <p>Guidelines for categories</p>

  <div class="">
  <%= form_for @category do |f| %>
    <div class="">
      <%= f.hidden_field :parent_id, :value => @category.parent_id %>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="">
      <%= f.submit "Save" %>
    </div>
  <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <h1>All Categories</h1>

  <%= link_to "Add new category", new_category_path()%><br /><br />

  <% @categories.each do |category| %>
    <h4><%= link_to category.name, category %> <small><%= link_to "Edit", edit_category_path(id: category.id)%> | <%= link_to "Remove", category, :method => :delete %> | <%= link_to "Add subcategory", new_category_path(id: category.id)%></small></h4>

      <% category.subcategories.each do |subcategory| %>
        <h5><%= link_to subcategory.name, subcategory %> <small><%= link_to "Edit", edit_category_path(id: category.id)%> | <%= link_to "remove", subcategory, :method => :delete %></small></h5>

      <% end %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<div class="row">
  <p>Guidelines for categories</p>

  <div class="">
  <%= form_for @category do |f| %>
    <div class="">
      <%= f.hidden_field :parent_id, :value => @category.parent_id %>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="">
      <%= f.submit "Save" %>
    </div>
  <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %> <small><%= link_to "Edit", edit_category_path(@category), class: '' %></small></h1>

  <% if @subcategories %>
  <ul>
    <% @subcategories.each do |subcategory| %>
      <li><%= link_to subcategory.name, subcategory %></li>
    <% end %>
  </ul>
  <% end %>

  <% if @events %>
    <% @events.each do |event| %>
      <h4><%= link_to event.title, [@category, event] %></h4>
    <% end %>
  <% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<div class="row">
  <p>Guidelines for events</p>

  <div class="">
  <%= form_for [@category, @event] do |f| %>
    <div class="">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <div class="">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>

    <div class="">
      <%= f.label :category %>
      <%= f.collection_select :category_ids, @subcategories, :id, :name, prompt: "Select One" %>
    </div>

    <div class="">
      <%= f.submit "Save" %>
    </div>
  <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <h1>All Events</h1>
  <% @events.each do |event| %>
    <h4><%= link_to event.title, [@category, event] %></h4>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<div class="row">
  <p>Guidelines for events</p>

  <div class="">
  <%= form_for [@category, @event] do |f| %>
    <div class="">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <div class="">
      <%= f.label :price %>
      <%= f.text_area :price %>
    </div>

    <div class="">
      <%= f.label :category %>
      <%= f.collection_select :category_ids, @categories, :id, :name, prompt: "Select One" %>
    </div>

    <div class="">
      <%= f.submit "Save" %>
    </div>
  <% end %>
  </div>
</div>

app/views/events/show.html.erb
<p>Category: <%= @event.categories.first.name %></p>

<h1><%= @event.title %> <small><%= link_to "Edit", edit_category_event_path(@category, @event), class: '' %></small></h1>



<p>Description: <%= @event.body %></p>
<p>Price: <%= @event.price %></p>

<% if @event.venues.first %>
  <p>Venue: <%= @event.venues.first.name %></p>
  <p>Address: <%= @event.venues.first.address %></p>
  <p>Phone: <%= @event.venues.first.phone %></p>
  <p>Website: <%= @event.venues.first.website %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pippin" %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name"><h1><%= link_to "Pippin", root_path %></h1></li>
      </ul>

      <section class="top-bar-section">

        <ul class="right">
          <% if current_user %>
            <li>Hello <%= current_user.email %>!</li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>

        <ul class="left">
          <li class="name"><%= link_to "About", about_path %></li>
        </ul>

      </section>
    </nav>

    <div class="row">
      <% if flash[:notice] %>
        <div class="alert-box radius success">
          <button type ="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert-box radius alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert-box radius secondary">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <div class="row">
    <%= yield %>
    
    </div>
  </body>

</html>

app/views/venues/edit.html.erb
<h1>Edit Venue</h1>

<div class="row">

  <div class="">
  <%= form_for @venue do |f| %>
    <div class="">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <div class="">
      <%= f.label :address %>
      <%= f.text_area :address %>
    </div>
    <div class="">
      <%= f.label :phone %>
      <%= f.text_area :phone %>
    </div>
    <div class="">
      <%= f.label :website %>
      <%= f.text_area :website %>
    </div>
    <div class="">
      <%= f.submit "Save" %>
    </div>
  <% end %>
  </div>
</div>

app/views/venues/index.html.erb
<h1>All Venues</h1>
<% @venues.each do |venue| %>
  <p><%= link_to venue.name, venue %></p>
<% end %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<div class="row">

  <div class="">
  <%= form_for @venue do |f| %>
    <div class="">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <div class="">
      <%= f.label :address %>
      <%= f.text_area :address %>
    </div>
    <div class="">
      <%= f.label :phone %>
      <%= f.text_area :phone %>
    </div>
    <div class="">
      <%= f.label :website %>
      <%= f.text_area :website %>
    </div>
    <div class="">
      <%= f.submit "Save" %>
    </div>
  <% end %>
  </div>
</div>

app/views/venues/show.html.erb
<h1><%= @venue.name %></h1>

<%= link_to "Edit", edit_venue_path(@venue), class: '' %>

<p><%= @venue.body %></p>
<p><%= @venue.address %></p>
<p><%= @venue.phone %></p>
<p><%= @venue.website %></p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>